### ISSUE TITLE
Redefinition bugs

### ISSUE THREAD

**Issue by tmpfs** [jshint/jshint#2876]
I am not sure if this is my mistake but it seems like a bug to me, `jshint v2.9.1`.

I am getting redefinition warnings on:

```
var setup = require('../setup/home');
```

And:

```
var suite = new benchmark.Suite();
```

Feel free to correct me but this appears to be a regexp/comparison that is a little too simple.

**Comment by nicolo-ribaudo** [comment]
You are declaring the `setup` var two times. You have to omit the `var` keyword in the second line.

**Comment by tmpfs** [comment]
@nicolo-ribaudo , I got your comment in my email but the github interface is not showing it right now (probably a caching bug), you said:

> You are declaring the setup var two times. You have to omit the var keyword in the second line.

This is the file:

https://github.com/tmpfs/rlx/blob/master/test/util/teardown/home.js

This is the error message:

```
test/util/teardown/home.js: line 1, col 5, Redefinition of 'setup'.
```

I don't see any redefinition there. The second example I just renamed the variable to avoid it but trust me there was no redefinition ;)

**Comment by tmpfs** [comment]
Please try it, create a file where the require path has the same string as the variable name, ie:

```
var setup = require('../setup/home');
```

Then run `jshint` on it, I get:

```
jshint test/util/teardown/home.js
test/util/teardown/home.js: line 1, col 5, Redefinition of 'setup'.
test/util/teardown/home.js: line 1, col 5, 'setup' is defined but never used.
```

Obvously the second error is irrelevant because I deleted everything else in the file to test it.

**Comment by tmpfs** [comment]
Also please try the second example in a standalone file, I am sure there was no redefinition.

Do you want me to create more files to reproduce the issues for you?

**Comment by nicolo-ribaudo** [comment]
@tmpfs I deleted my comment because I saw I was wrong

**Comment by tmpfs** [comment]
Neither it appears, `.jshintrc` looks like this for the project:

```
{
  "laxcomma"                : true,
  "laxbreak"                : true,
  "node"                    : true,
  "curly"                   : true,
  "bitwise"                 : false,
  "undef"                   : true,
  "eqeqeq"                  : true,
  "noarg"                   : true,
  "mocha"                   : true,
  "unused"                  : true,
  "asi"                     : true
}
```

Any ideas? Do you want me to try to reproduce this in isolation?

**Comment by tmpfs** [comment]
I think it might be a regression because I only started to come across this after upgrading to 2.9.1, sadly I forget which version I was using before.

**Comment by nicolo-ribaudo** [comment]
`setup` and `suite` are predefined by mocha (http://mochajs.org/ ~ see the TDD section)

**Comment by tmpfs** [comment]
The `suite` issue was to do with [benchmark](https://github.com/bestiejs/benchmark.js) so this is potentially to do with `jshint` seeing global variables already set and then warning on a possible redefine?

I am not sure this is the cause of the problem, why then when I save the file in `vim` and it is executed via `jshint` do I also get the same error - this is what caused me to actually raise the issue. In that case there should not be any other files being passed to `jshint` so there is no potential pollution by other libraries.

**Comment by tmpfs** [comment]
Ok, I have taken everything out and I still get the error.

Required file:

```
module.exports = {};
```

File to lint:

```
var setup = require('../setup/home');
```

Command:

```
jshint test/util/teardown/home.js
```

Result:

```
test/util/teardown/home.js: line 1, col 5, Redefinition of 'setup'.
test/util/teardown/home.js: line 1, col 5, 'setup' is defined but never used.
```

So, I think we can rule out predefined globals causing a collision.

**Comment by tmpfs** [comment]
This should help you reproduce the issue in isolation to determine if it is a bug:

https://github.com/tmpfs/jshint-redef

The first test does not require any other files so I fail to see how this is not a bug.

**Comment by tmpfs** [comment]
BTW, don't get me wrong I really, really like `jshint` and use it heavily - the philosophy of separating style from correctness is good. If you determine this is a bug I am happy to try to help you fix it, because well it's bugging me ;)

**Comment by jugglinmike** [comment]
Wow, thanks for doing all the legwork on this one, @tmpfs! I'm having trouble reproducing either bug. Here's my output:

    $ ./node_modules/.bin/jshint redef-1.js
    $

    $ ./node_modules/.bin/jshint redef-2.js 
    redef-2.js: line 2, col 3, Comma warnings can be turned off with 'laxcomma'.
    redef-2.js: line 1, col 36, Bad line breaking before ','.

    2 errors
    $

Some things to note:

- I am using the `./node_modules/.bin/jshint`, the executable defined within the `node_modules` directory. In your sample project's "readme" file, it demonstrates the invocation using a "bare" reference to `jshint`. You may have configured your PATH to include `./node_modules/.bin`, but you may also be running with a different installation (and different version) of JSHint.
- In the first invocation, I do not see any errors at all. This is consistent with the documented default behavior of JSHint. The second warning you've reported ("'setup' is defined but never used.") should only be emitted if JSHint is configured with `unused`. As a "enforcing option", it should *not* be enabled by default. This makes me think that the sample project may be missing a `.jshintrc` file. As a dotfile, it can be easy to miss! But then again, it might just be a sign of a different kind of bug.

Could you confirm that this behavior persists when you use the local installation of JSHint? And can you determine if there are any configuration files missing from the repository as it exists on GitHub?

**Comment by tmpfs** [comment]
Indeed `./node_modules/.bin` is preferred in PATH when executing (building the readme).

My `~/.jshintrc` looks like:

```
{
  "laxcomma"                : true,
  "laxbreak"                : true,
  "node"                    : true,
  "curly"                   : true,
  "bitwise"                 : false,
  "undef"                   : true,
  "eqeqeq"                  : true,
  "noarg"                   : true,
  "mocha"                   : true,
  "unused"                  : true,
  "asi"                     : true
}
```

As I haven't added a project specific rc file I guess that one is being used.

```
./node_modules/.bin/jshint --version
jshint v2.9.1
```

So version is correct. And my direct invocation is (to rule out conflict with globally installed version - which is the same version):

```
./node_modules/.bin/jshint redef-1.js

redef-1.js: line 1, col 5, Redefinition of 'setup'.
redef-1.js: line 1, col 5, 'setup' is defined but never used.

2 errors
```

When I move away `~/.jshintrc` the errors go away :)

I can't see what it is in the global config that is causing the redefinition problem, I have moved it into the repository and committed (no more global `~/.jshintrc` for me!).

With that `.jshintrc` as a project level rc file the redefinition errors come back - please what is it in that config that is wrong?

**Comment by tmpfs** [comment]
Direct link to file:

https://github.com/tmpfs/jshint-redef/blob/master/.jshintrc

**Comment by tmpfs** [comment]
Note that the `unused` error is expected (and wanted), it is the redefinition error that I think is a false positive.

**Comment by tmpfs** [comment]
It's `mocha` right? So when that is enabled it set's `predef` for `suite` and `setup`? Like you originally thought ;)

**Comment by tmpfs** [comment]
If I am correct that `predef` is set when `mocha` is enabled then I think the behaviour should be changed so that they are not set as `predef` but only detected *when mocha is in use*. I don't think this is a bug per se, my lack of understanding, however maybe you can see how this behaviour is very confusing. Especially in the second example where `mocha` was not being used at all.

What do you think?

**Comment by tmpfs** [comment]
The other thing of course is that when I use `var` in a module I expect the variable to be local to that module, however, if I had omitted the `var` then I would expect the redefinition warning.

**Comment by tmpfs** [comment]
Note that quick anecdotal evidence creating a new project this also might apply to `before` and `after`.

**Comment by jugglinmike** [comment]
> If I am correct that predef is set when mocha is enabled then I think the
> behaviour should be changed so that they are not set as predef but only
> detected when mocha is in use.

That kind of behavior would probably surprise many people.

> The other thing of course is that when I use var in a module I expect the
> variable to be local to that module, however, if I had omitted the var then I
> would expect the redefinition warning.

I agree with you on this. I have submitted a patch so that in Node.js
environments, JSHint recognizes that `var` statements in seemingly-global code
do *not* resolve to the global bindings--see gh-2877.

So while JSHint is definitely misbehaving here, I recommend that you extend
your configuration to only enable the `mocha` option for files that are
actually executed in an environment where `mocha` has been loaded. This is not
simply a workaround to the bug; it's actually safer overall. When your entire
project is configured with `mocha: true`, JSHint cannot consistently detect
references to undefined variables.

For instance, a source file that is *not* executed with Mocha might contain the
expression `test(123)` without a corresponding declaration for `test`, and
JSHint would not issue a warning. That will be a risk even when the underlying
bug is fixed.

This can be done by creating distinct configuration files for different
directories within your project. In the case of https://github.com/tmpfs/rlx,
that would involve a new file at `test/.jshintrc`.  You can limit duplication
by using [the `extends` option](http://jshint.com/docs/cli/).

**Comment by tmpfs** [comment]
@jugglinmike Thank you for the clear response. I will take your advice and use `extends` in the `test` directory.

@jugglinmike, @nicolo-ribaudo Thank you for your help on this issue and for `jshint` which has become invaluable to me.

I have learnt a lot from this, not least of all `~/.jshintrc` is a bad idea, but also how I can configure my projects for a better linting experience. Apologies that I assumed that this as a bug in `jshint`.

An impeccable response from an OSS project which is sometimes hard to come by here on github.

Closing as resolved, re-open if you feel that https://github.com/jshint/jshint/pull/2877 should be merged before this is closed.
