### ISSUE TITLE
JSHint throws an error when including it as a requirejs module

### ISSUE THREAD

**Issue by Sriram-Ramaswami** [jshint/jshint#2840]
Hi,

As part of a POC I am developing, I have prepared a small sample that will allow my angular app to work with requirejs. Now I am planning to integrate JsHint. The only requirement is that there is no nodejs.

I have taken the js file from the dist folder of the release and loaded it as a require module. But when doing so, I get the following error
![jshint_error](https://cloud.githubusercontent.com/assets/11866198/12472402/dd389d7c-c02d-11e5-9e8d-d9d47c452fe1.png)

Uncaught TypeError: _.each is not a function

All the other modules that I have loaded through require are fine like bootstrap and angular. I have tried including underscore.js and load it before jshint but to no avail.

Is this a bug with jshint or am I doing something wrong. below is the code for my requirejs bootstrapping

require.config({
    baseUrl: 'scripts',
    paths: {
		'jshint':'lib/jshint/jshint',
		'angular': 'lib/angular/angular.min',
		'angular-route': 'lib/angular/angular-route.min'

    },
	shim: {
		'app': {
			deps: ['jshint','angular', 'angular-route']
		},
		'angular-route': {
			deps: ['angular']
		}
	}
});

require
(
    [
        'app'
    ],
    function(app)
    {
        angular.bootstrap(document, ['app']);
    }
);

**Comment by caitp** [comment]
I would expect that underscore is not marked as a dependency of jshint. Also, modern jshint is using lodash, so there may be some compat issues with lodash, though i doubt it.

Just spitballin

**Comment by BoykoAlex** [comment]
I have faced the same issue... Any workarounds?

**Comment by orionlee** [comment]
Somehow the presence of requirejs (or maybe AMD in general) makes loading lodash fails.
It works in v2.6.3, but it starts to fail in v2.7.0

I have a sample showing it [sample with v2.9.3](https://jsfiddle.net/t05qwyk8/). The error from Developer tools:
```
VM104 jshint.js:15777 
Uncaught TypeError: _.each is not a function
  require.14.lodash @ VM104 jshint.js:15777
  s @ VM104 jshint.js:6
  (anonymous function) @ VM104 jshint.js:6
  ...
```

In contrast, 
- [sample with JSHINT v2.6.3](https://jsfiddle.net/t05qwyk8/1/) works;
- [sample with v.2.7.0](https://jsfiddle.net/t05qwyk8/2/) starts to fail.

Any idea?

**Comment by jlchereau** [comment]
Same thing with SystemJS (but not with webpack)

**Comment by nunes-bruno-m** [comment]
> Somehow the presence of requirejs (or maybe AMD in general) makes loading lodash fails.
> It works in v2.6.3, but it starts to fail in v2.7.0
> 
> I have a sample showing it [sample with v2.9.3](https://jsfiddle.net/t05qwyk8/). The error from Developer tools:
> 
> ```
> VM104 jshint.js:15777 
> Uncaught TypeError: _.each is not a function
>   require.14.lodash @ VM104 jshint.js:15777
>   s @ VM104 jshint.js:6
>   (anonymous function) @ VM104 jshint.js:6
>   ...
> ```
> 
> In contrast,
> 
> * [sample with JSHINT v2.6.3](https://jsfiddle.net/t05qwyk8/1/) works;
> * [sample with v.2.7.0](https://jsfiddle.net/t05qwyk8/2/) starts to fail.
> 
> Any idea?

After 2.6.3 it changed from Underscore to Lodash.
Check the 'var _ = require("underscore");' in 2.6.3 and 'var _ = require("lodash");' in 2.12.10

**Comment by shubhamwingify** [comment]
Hi, any workaround for this issue?

**Comment by davhdavh** [comment]
6 years later and still didnt implement this 1 line fix?!?
![image](https://user-images.githubusercontent.com/1201165/201818320-f8427db6-640f-41a8-a598-449e50a2a94c.png)
