### ISSUE TITLE
Redefinition of 'context' errors in 2.6.3

### ISSUE THREAD

**Issue by kenperkins** [jshint/jshint#2229]
This appears to be related to #2213.

https://github.com/pkgcloud/pkgcloud Travis tests have started failing with `package.json` having `devDependencies` of `"jshint":"2.x.x"`. Our jshint test output shows two Redefinition errors that did not manifest in `2.5.x`.

https://jslinterrors.com/redefinition-of-a

```
lib/pkgcloud/openstack/client.js: line 12, col 5, Redefinition of 'context'.

test/openstack/identity/service-test.js: line 1, col 5, Redefinition of 'context'.
```

**Comment by rwaldron** [comment]
I can repro, but unclear why/how this changed.

**Comment by rwaldron** [comment]
Found it: 

```
$ git bisect bad
8fe661018106e3534c81182effa8db1477a594e0 is the first bad commit
commit 8fe661018106e3534c81182effa8db1477a594e0
Author: Haoliang Gao <sakura9515@gmail.com>
Date:   Fri Jan 30 01:01:33 2015 +0800

    [[FIX]] Miss xdescribe/xit/context/xcontext in mocha

    Relate jshint/jshint#2057 mochajs/mocha#429

:040000 040000 def5319f194ee9d817960ceb2f23d54c37535350 40d0f62b0b97ff71ff810edfcbb4f42e0e2e396a M	src
```


Nothing about options or settings changed—a fellow mocha user contributed a patch that added missing  mocha vars: https://github.com/jshint/jshint/commit/8fe661018106e3534c81182effa8db1477a594e0

It makes sense to warn about these, just as it does for any other predefined environment var that JSHint protects. If the project wants the freedom to pave over vars that are protected by environment identifier lists (that are explicitly opted into, ie. mocha), the easiest fix is to add: `predef: ["-context"]` to .jshintrc

**Comment by kenperkins** [comment]
Thanks for the quick turn-around.

**Comment by kenperkins** [comment]
While I appreciate the insight, this still feels like a breaking change; I shouldn't have to change my `.jshintrc` file to make a non SemVer-major version work.

**Comment by rwaldron** [comment]
The fact that no warning existed prior to that patch was a bug—the bug was fixed. No regression or unit tests were broken in JSHint. I'm not trying to be unreasonable, but I think a major or minor version release for a tiny bug fix is _unreasonable_. That said, I will make an effort to spend more time running release builds and generating changelogs for finer grained minor releases.

**Comment by kenperkins** [comment]
I agree.  I suppose it's a side-effect of SemVer. Bug fixes that break previous versions should not be major versions, but these will inevitably happen.

Thanks for your time!

**Comment by rwaldron** [comment]
I appreciate your patience and understanding :)
